<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 19/5/21
 * Time: 下午3:17
 */

namespace app\manage\controller;


use app\manage\base\LoginBaseController;
use app\manage\model\FieldsModel;

class FieldsController extends LoginBaseController {

    private $_model;

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_model = new FieldsModel();
    }

    //获取字段列表
    public function indexDo(){
        $list = $this->_model->getList();
        $page = $list->render();
        $this->assign('list', $list);
        $this->assign('page', $page);
        return $this->fetch();
    }

    public function addDo(){
        $this->post();
    }

    public function editDo(){
        $this->post();
    }

    public function deleteDo(){
        if(request()->isAjax()){
            $id = input('id',0);
            $this->_model->del($id);
        }
    }

    protected function post(){
        $id = input('id',0);
        if(request()->isPost()){
            $data = array(
                'title' => input('post.title',''),
                'sign'  => input('post.sign', '')
            );
            if(empty($id)){
                $id = $this->_model->add($data);
            }else{
                $id = $this->_model->edit($id, $data);
            }

            $this->success('操作成功!', url('manage/fields/index'), 3);
        }

        $item = $this->_model->getOne($id);
        $this->assign('item', $item);
        $this->assign('id', $id);
        return $this->fetch();
    }
}