<?php
/**
 * 后台首页
 * Created by PhpStorm.
 * User: appleimac
 * Date: 19/3/21
 * Time: 上午9:23
 */

namespace app\manage\controller;


use app\manage\base\LoginBaseController;

class IndexController extends LoginBaseController {

    protected function init() {
        $this->systemTitle = '系统首页';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexDo(){
        return $this->fetch();
    }
}