<?php

/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 19/3/19
 * Time: 下午5:29
 */

namespace app\manage\base;

use think\Controller;
use think\Request;

abstract class BaseController extends Controller {
    protected $uid;
    protected $systemTitle;

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if($this instanceof LoginBaseController){
            if(!session('?uid','','login')){
                $ret = urlencode(Request::instance()->url());
                $this->redirect('Login/index', ['ret_url' => $ret]);
            }

            $this->uid = session('uid','','login');
        }

        $this->init();

        $this->assign('systemTitle', $this->systemTitle);
    }

    protected abstract function init();
}