<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 19/3/21
 * Time: 10:08
 */

namespace app\index\base;

class LoginBaseController extends BaseController {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('systemTitle', 'ϵͳ');
    }
}