<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 19/3/25
 * Time: 下午5:02
 */

namespace app\index\controller;


use app\index\base\LoginBaseController;
use app\model\DoubleModel;

class CharController extends LoginBaseController {

    protected $model;
    protected $yearList;
    protected $ball;

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new DoubleModel();
        $this->yearList = $this->model->getYearList();
        $this->ball = get_double_ball();
        $this->assign('year_list', $this->yearList);
        $this->assign('ball_title', $this->ball);
    }

    public function indexDo(){
        $year = input('get.year',0);
        $issue = input('get.issue', '');

        //默认为当前年份的数据显示
        if(empty($year)){
            $year = date('y', time());
        }else{
            $year -= 2000;
        }

        $condition['year'] = $year;

        if(!empty($issue)){
            if(strpos(',',$issue) === false && strpos('-',$issue) === false){
                $condition['issue_no'] = $issue;
            }elseif (strpos(',', $issue) !== false){
                $tmpIssue = explode(',',$issue);
                $condition['issue_no'] = ['in',$tmpIssue];
            }elseif (strpos('-', $issue) !== false){
                $tmpIssue = explode('-', $issue);
                $condition['issue_no'] = ['between',$tmpIssue];
            }
        }

        $list = $this->model->getNumberList($condition);
        var_dump($list);die();
        $this->assign('list', $list);
        return $this->fetch();
    }
}