<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 19/3/25
 * Time: 下午5:02
 */

namespace app\index\controller;


use app\index\base\LoginBaseController;
use app\model\DoubleModel;

class CharController extends LoginBaseController {

    protected $model;

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new DoubleModel();
        $this->getYearList();
    }

    protected function getYearList(){
        $info = $this->model->getYearList();
        var_dump($info);die();
    }

    public function indexDo(){


        return $this->fetch();
    }
}